version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  assignees:
  - sue445
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.13.0
