require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.1
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
