inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1

Layout/AlignHash:
  EnforcedColonStyle: table

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
