version: '3'

services:
  app:
    build: .
    working_dir: "/app"
    environment:
      - SLACK_WEBHOOK_URL
      - SLACK_CHANNEL
      - SLACK_USERNAME
      # - DEBUG_LOGGING=false
      # - PUMA_THREADS_MIN=0
      # - PUMA_THREADS_MAX=1
      # - PUMA_WORKERS=0
      # - PUMA_PORT=3000
    ports:
      - "3000:3000"
